services:
  database:
    container_name: postgres_container
    image: 'postgres:17beta2-alpine'
    restart: always
    env_file:
      - .env
    ports:
    - '5432:5432'
    volumes:
    - 'database:/var/lib/postgresql/data'
volumes:
  database:
    driver: local