FROM node:22-alpine

WORKDIR /

COPY package*.json ./

RUN npm install

COPY . .

# Runs index.js every 6 hours
RUN echo '0 */6 * * * node /index.js >> /var/log/cron.log 2>&1' > /etc/crontabs/root

CMD crond -f -L /var/log/cron.log